### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by C3R3S1** [t1f7/pythonstarships#1]
How can i fix the error of:
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: C:\Users\\Downloads\pythonstarships-main\pythonstarships-main\main.py
Traceback (most recent call last):
  File "C:\Users\\Downloads\pythonstarships-main\pythonstarships-main\main.py", line 1, in <module>
    from sdk.client import Client
  File "C:\Users\\Downloads\pythonstarships-main\pythonstarships-main\sdk\client.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by t1f7** [comment]
`pip3 install requests`
or just `pip install requests` if you have only python3 installed.
